### ISSUE TITLE
customfield_*

### ISSUE THREAD

**Issue by raikakhodadad1** [free/jiralert#8]
Hi, 

Do you have an example of a selectlist or multiselect list customfield working? What would the format be in jiralert.yml? I have tried to input the customfield multiple ways however wasn't able to get it working. See examples below what I tried:

1) 
```yaml
receivers:
  - name: 'jira-ab'
    project: TOSD 
    components: [ 'RMA' ]
    add_group_labels: false
    fields:
      customfield_10863: DCOPS
```
2) 
```yaml
receivers:
  - name: 'jira-ab'
    project: TOSD 
    components: [ 'RMA' ]
    add_group_labels: false
    fields:
      customfield_10863: {"value": "DCOPS"}
```
3) 
```yaml
receivers:
  - name: 'jira-ab'
    project: TOSD 
    components: [ 'RMA' ]
    add_group_labels: false
    fields:
      customfield_10863: |
        {"value": "DCOPS"}
```
4)
```yaml
receivers:
  - name: 'jira-ab'
    project: TOSD 
    components: [ 'RMA' ]
    add_group_labels: false
    fields:
      customfield_10863: |
        "value": "DCOPS"
```
